version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    container_name: sql-training-db
    environment:
      MYSQL_DATABASE: 'employees'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'learning'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'learning'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3326:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_data:/var/lib/mysql
# Names our volume
volumes:
  db_data:
